title = "Awesome Hugo blog"
baseURL = 'https://falconspy6015.github.io/'
languageCode = 'en-us'
defaultContentLanguage = "en-gb"
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] 
theme = "hugo-blog-awesome"

[Menus]
  [[Menus.main]]
    identifier = "blog"
    name = "Blog"
    title = "Blog posts"
    url = "/blogs"
    weight = 1

  [[Menus.main]]
    identifier = "gallery"
    name = "Gallery"
    title = "Blog posts"
    url = "/gallery"
    weight = 2

[hero]
enable = true
intro = "Hi, my name is"
title = "Isabella."
subtitle = "I build things for the web"
content = "A passionate web app developer. I tend to make use of modern web technologies to build websites that look great, feel fantastic, and function correctly."
image = "/images/hero.svg"

[hero.bottomImage]
enable = true

[hero.button]
enable = true
name = "Resume"
url = "#"
download = true
newPage = false

[hero.socialLinks]
  [[hero.socialLinks.fontAwesomeIcons]]
  icon = "fab fa-github"
  url = "https://example.com"

  [[hero.socialLinks.fontAwesomeIcons]]
  icon = "fab fa-x-twitter"
  url = "https://example.com"

  [[hero.socialLinks.customIcons]]
  icon = "/fav.png"
  url = "https://example.com"


[about]
enable = true
title = "About Me"
image = "/images/me.png"
content = """I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA.

I am currently working on a project that will be used to help people find the best way to get around the city."""

[about.skills]
enable = true
title = "Here are a few technologies I've been working with recently:"
items = [
  "HTML",
  "CSS",
  "JavaScript",
  "React",
  "Node",
  "Express"
]



[params]
  goToTop = true

[services]

  [services.googleAnalytics]
 
