baseurl = "/"
languageCode = "en-us"
theme = "hugo-blog-awesome"
paginate = 5

# General Parameters
[params]
  contentTypeName = "posts"
  showMenuItems = 3   # Show 3 menu items, can be adjusted
  showLanguageSelector = false
  fullWidthTheme = true  # Use the full width theme for a more modern look
  centerTheme = true     # Center theme content for better readability
  autoCover = true       # Automatically use cover images if available
  showLastUpdated = true # Show last updated date on posts
  showPostsOnHomepage = true

  # Optional: Customize the homepage description (for SEO and layout)
  homeDescription = "Welcome to my blog, where I explore technology, programming, and life."
  homepageBackground = "#f7f7f7"  # Soft background color for the homepage

  # Social media (adjust these if you want to link your social media)
  [params.social]
    twitter = "your-twitter-handle"
    github = "your-github-handle"
    linkedin = "your-linkedin-handle"

  # Logo settings (you can change this to match your style)
  [params.logo]
    logoText = "Falconspy6015"
    logoHomeLink = "/"

  # Table of contents settings (optional)
  Toc = true
  TocTitle = "Table of Contents"

  # Enable/disable certain post features
  enableReadingTime = true    # Display reading time on posts
  enableComments = false      # You can enable this if you want comments on your posts

# Menu settings for navigation links
[languages]
  [languages.en]
    languageName = "English"
    title = "Falconspy6015 Blog | Tech & Programming"

    [languages.en.params]
      subtitle = "Connecting to the world one post at a time"
      owner = "Falconspy6015"
      keywords = "technology, programming, blog"
      copyright = "2024 Falconspy6015. All rights reserved."
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      # Navigation menu
      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/about"
          weight = 1

        [[languages.en.menu.main]]
          identifier = "showcase"
          name = "Showcase"
          url = "/showcase"
          weight = 2

        [[languages.en.menu.main]]
          identifier = "contact"
          name = "Contact"
          url = "/contact"
          weight = 3  # Add a contact page if necessary

        [[languages.en.menu.main]]
          identifier = "blog"
          name = "Blog"
          url = "/posts"
          weight = 4  # Link to blog post list

# Optional: Settings for post listing page
[permalinks]
  posts = "/posts/:year/:month/:day/:slug/"

