title = "FalconBlog"
baseURL = 'https://falconspy6015.github.io/'
languageCode = 'en-us'
defaultContentLanguage = "en-gb"
enableEmoji = true

theme = "hugo-blog-awesome"

[Menus]
  [[Menus.main]]
    identifier = "blog"
    name = "Blog"
    title = "Blog posts"
    url = "/posts/"
    weight = 1

  [[Menus.main]]
    identifier = "About"
    name = "About"
    title = "About Myself"
    url = "/about/"
    weight = 2
    
  [[Menus.main]]
    identifier = "Showcase"
    name = "Showcase"
    title = "My milestones"
    url = "/showcase/"
    weight = 3


[Languages.en-gb.params]
  sitename = "FalconBlog"
  defaultColor = "dark" 
  description = "A space where creativity meets expression, and ideas come to life."
  mainSections = ['posts']
  toc = true # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' button
  dateFormat = ""
  rssFeedDescription = "summary" # available options: 1) summary 2) full
  # summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .
  # full - includes full blog post in the RSS feed. Generated using Hugo .Content .
  # By default (or if nothing is specified), summary is used.

[Languages.en-gb.params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "FalconBlog"
  name = "Falconspy6015"
  description = "A space where creativity meets expression, and ideas come to life."
 content = """"Welcome to my blog! I'm a first-year B.Tech student in Electrical Engineering at IIT Madras with a passion for technology and innovation. Here, I share my thoughts, projects, and discoveries in areas like cybersecurity, web and app development, and programming. This blog is my space to document my journey, exchange ideas, and hopefully inspire others in the tech community. Join me as I explore, learn, and create!"""
[params.about]
enable = true
title = "Welcome to My Blog"
content = """"Welcome to my blog! I'm a first-year B.Tech student in Electrical Engineering at IIT Madras with a passion for technology and innovation. Here, I share my thoughts, projects, and discoveries in areas like cybersecurity, web and app development, and programming. This blog is my space to document my journey, exchange ideas, and hopefully inspire others in the tech community. Join me as I explore, learn, and create.Thank you for visiting!"""

# Allow to override webmanifest options
[Languages.en-gb.params.webmanifest]
  name = "sitename" # will use "params.sitename" or "title" by default
  short_name = "sitename" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"


[services]

  [services.googleAnalytics]
 
